server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 20000
    max-connections: 8192
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain

spring:
  application:
    name: smooth-operators-api
  
  # Async configuration
  task:
    execution:
      pool:
        core-size: 8
        max-size: 20
        queue-capacity: 100
      thread-name-prefix: async-exec-
    scheduling:
      pool:
        size: 4

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Custom application properties
app:
  fibonacci:
    max-input: 50
    timeout-seconds: 5
    cache-size-limit: 1000
  monitoring:
    enabled: true
    log-slow-requests: true
    slow-request-threshold-ms: 1000

# Logging configuration
logging:
  level:
    com.smoother.operators: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
